-d D:\Hardware\FPGA\LED_button\impl\gwsynthesis\LED_button.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Hardware\FPGA\LED_button\src\LED_control.cst
-cfg D:\Hardware\FPGA\LED_button\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
