-d D:\Hardware\FPGA\LED_prj\impl\gwsynthesis\LED_prj.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Hardware\FPGA\LED_prj\src\LED_prj.cst
-cfg D:\Hardware\FPGA\LED_prj\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
